function crosscheck(stage)
%CROSSCHECK  ONE entry point for MODEL.md check (i). Runs every stage in order, stops at the first
%   failure, and writes everything it prints to simscape/crosscheck_log.txt - send me that file.
%
%   crosscheck            all stages, then the 'step' case only
%   crosscheck('all')     all stages, then all eight cases
%   crosscheck({'step_sm','high_z_48_sm'})   all stages, then just these cases
%   crosscheck('rebuild') force a fresh port detection and model build first
%
%   Stages: 0 reference data (Python)  1 port conventions  2 build  3 verify  4 smoke test  5 cases
if nargin < 1, stage = 'step'; end
caselist = {};
if iscell(stage), caselist = stage; stage = 'list'; end
evalin('base', 'clear functions'); rehash;          % never run a stale cached copy of these scripts
P = project_paths();
here = fullfile(P.root, 'simscape');
old = cd(here); back = onCleanup(@() cd(old)); %#ok<NASGU>
logf = fullfile(here, 'crosscheck_log.txt');
if exist(logf, 'file'), delete(logf); end
diary(logf); stopdiary = onCleanup(@() diary('off')); %#ok<NASGU>
fprintf('crosscheck %s   MATLAB %s   %s\n', stage, version, char(datetime('now')));
fprintf('scripts: %s\n', shelf_build_tag());
need = {'print_error', 'ensure_cases', 'detect_ports', 'shelf_build_tag'};
miss = need(cellfun(@(f) exist(f, 'file') ~= 2, need));
if ~isempty(miss), fprintf('MISSING FILES: %s  -> the update zip was not extracted into <repo>/simscape\n', strjoin(miss, ', ')); return, end

try
fprintf('\n===== stage 0: reference data\n');
ensure_cases(P.data); fprintf('ok: %s\n', P.data);

fprintf('\n===== stage 1: port conventions\n');
fresh = strcmp(stage, 'rebuild');
detected = false;
if fresh || ~contains(fileread(fullfile(here, 'shelf_ports.m')), 'GENERATED by detect_ports')
    detect_ports(); detected = true;
end
if test_conventions() > 0
    if ~detected, fprintf('stored conventions fail - detecting again\n'); detect_ports(); end
    if detected || test_conventions() > 0, fprintf('\nSTOP at stage 1.\n'); return, end
end
fprintf('\n--- shelf_ports.m in use:\n%s\n', fileread(fullfile(here, 'shelf_ports.m')));

fprintf('\n===== stage 2: build\n');
slx = fullfile(here, 'dcsim_shelf.slx'); stale = true;
if ~fresh && exist(slx, 'file')
    load_system(slx); stale = ~strcmp(get_param('dcsim_shelf', 'Description'), shelf_build_tag());
    if stale, fprintf('existing dcsim_shelf.slx was made by an older builder - rebuilding\n'); end
end
if stale
    build_dcsim_shelf('dcsim_shelf'); fprintf('built: %s\n', shelf_build_tag());
else
    fprintf('dcsim_shelf.slx is current - kept\n');
end

fprintf('\n===== stage 3: verify\n');
if ~verify_build(), fprintf('\nSTOP at stage 3.\n'); return, end

fprintf('\n===== stage 4: smoke test (flat at the Python steady state before the event)\n');
if ~smoke_test(), fprintf('\nSTOP at stage 4.\n'); return, end

fprintf('\n===== stage 5: cases\n');
if strcmp(stage, 'all'), run_all_cases(); elseif ~isempty(caselist), run_all_cases(caselist); else, run_all_cases({'step'}); end
fprintf('\ndone. Log: %s\n', logf);
catch err
    fprintf('\nERROR - full cause tree:\n'); print_error(err);
    fprintf('\nstack:\n'); for q = 1:numel(err.stack), fprintf('    %s  line %d\n', err.stack(q).name, err.stack(q).line); end
end
end
