function P = shelf_ports()
%SHELF_PORTS  Simscape port conventions for build_dcsim_shelf.m.
%   GENERATED by detect_ports.m on 2026-09-17 23:52 (MATLAB 2026a). Do not edit by hand; re-run detect_ports.
%   p/n meaning: sources and sensors as labelled by the numeric tests in test_conventions.m
%   (ccs/dcs: current is DRAWN from the node on p; dio: p is the anode; cap: v = p - n; ind: i flows p -> n).
P.cvs.ctl = 'RConn1'; P.cvs.p = 'LConn1'; P.cvs.n = 'RConn2';
P.ccs.ctl = 'RConn1'; P.ccs.p = 'RConn2'; P.ccs.n = 'LConn1';
P.sw.ctl = 'RConn1'; P.sw.p = 'LConn1'; P.sw.n = 'RConn2';
P.isen.out = 'RConn1'; P.isen.p = 'LConn1'; P.isen.n = 'RConn2';
P.vsen.out = 'RConn1'; P.vsen.p = 'LConn1'; P.vsen.n = 'RConn2';
P.two.p = 'LConn1'; P.two.n = 'RConn1';
P.cap.p = 'LConn1'; P.cap.n = 'RConn1';
P.ind.p = 'LConn1'; P.ind.n = 'RConn1';
P.dio.p = 'LConn1'; P.dio.n = 'RConn1';
P.dcs.p = 'RConn1'; P.dcs.n = 'LConn1';
P.ref = 'LConn1'; P.solv = 'RConn1';
P.s2p.in = '1'; P.s2p.out = 'RConn1';
P.p2s.in = 'LConn1'; P.p2s.out = '1';
end
