/* fx_filters_data.h — generated by firmware/tools/export_filters.py (scipy 1.18.1);
 * do not edit. Coefficients are exact double literals; they convert to fx_iir_t at use.
 *   FX_SOS_BP: signal.butter(4, [1e3, 100e3], btype="bandpass", fs=500e3, output="sos")
 *   FX_SOS_AA: signal.butter(4, 0.4 * 5e3, fs=500e3, output="sos")   (synth._aa_decimate)
 *   FX_AA_ZI:  signal.sosfilt_zi(FX_SOS_AA), to be scaled by the first sample */
#ifndef FX_FILTERS_DATA_H
#define FX_FILTERS_DATA_H
#include "fx_filters.h"

static const fx_sos_t FX_SOS_BP[FX_N_SOS_BP] = {
    { 0x1.71ad45ce5af83p-5, 0x1.71ad45ce5af83p-4, 0x1.71ad45ce5af83p-5, -0x1.60b5c61747c78p-2, 0x1.178cdace10c90p-4 },
    { 0x1.0000000000000p+0, 0x1.0000000000000p+1, 0x1.0000000000000p+0, -0x1.d5485f86e2862p-2, 0x1.e3c2a19a91797p-2 },
    { 0x1.0000000000000p+0, -0x1.0000000000000p+1, 0x1.0000000000000p+0, -0x1.fa02e9272cf76p+0, 0x1.f41ae5de07c09p-1 },
    { 0x1.0000000000000p+0, -0x1.0000000000000p+1, 0x1.0000000000000p+0, -0x1.fd8a1069763a3p+0, 0x1.fb28d47903542p-1 }
};

static const fx_sos_t FX_SOS_AA[FX_N_SOS_AA] = {
    { 0x1.9ea83b6121169p-26, 0x1.9ea83b6121169p-25, 0x1.9ea83b6121169p-26, -0x1.f43978f9bc0ecp+0, 0x1.e8c3dac1ac770p-1 },
    { 0x1.0000000000000p+0, 0x1.0000000000000p+1, 0x1.0000000000000p+0, -0x1.faf6812267826p+0, 0x1.f63f021770cf7p-1 }
};

static const double FX_AA_ZI[FX_N_SOS_AA][2] = {
    { 0x1.47f255454f756p-13, -0x1.390fd5a5a0e52p-13 },
    { 0x1.ffeb800b5726dp-1, -0x1.f62a8222c7f84p-1 }
};

#endif /* FX_FILTERS_DATA_H */
