"""export_filters.py — scipy SOS coefficients -> firmware/common/fx_filters_data.h, and the
unit-test vectors -> firmware/host/tests/fx_test_vectors.h (FIRMWARE_SPEC.md §2, §3).

Run from the repo root with the venv python:  python firmware/tools/export_filters.py

Also re-derives every sample count of fx_config.h from the Python expressions and refuses
to run if one differs (the C unit test asserts the same values at run time)."""
import os
import sys
import numpy as np
from scipy import signal
import scipy

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
sys.path.insert(0, ROOT)
from dcsim.features import _movavg          # noqa: E402
from dcsim.synth import _aa_decimate        # noqa: E402

FS = 500e3
F_SLOW = 5e3
DECIM = 100
COMMON = os.path.join(ROOT, "firmware", "common")
TESTS = os.path.join(ROOT, "firmware", "host", "tests")


def hx(v):
    """exact C99 hex literal of a double"""
    v = float(v)
    if np.isnan(v):
        return "NAN"
    if np.isinf(v):
        return "INFINITY" if v > 0 else "-INFINITY"
    return v.hex()


def hxf(v):
    return float(np.float32(v)).hex() + "f"


def check_constants():
    fs = FS
    n_pre = max(int(0.15e-3 * fs), 4)
    got = dict(FX_N_PRE=n_pre, FX_N_SM5=max(int(5e-6 * fs), 1), FX_N_SM10=max(int(10e-6 * fs), 1),
               FX_N_50US=max(int(50e-6 * fs), 1), FX_N_SKIP=min(int(60e-6 * fs), n_pre - 3),
               FX_N_W_025=max(int(0.25e-3 * fs), 4), FX_N_W_050=max(int(0.5e-3 * fs), 4),
               FX_N_W_100=max(int(1e-3 * fs), 4))
    exp = dict(FX_N_PRE=75, FX_N_SM5=2, FX_N_SM10=5, FX_N_50US=25, FX_N_SKIP=30,
               FX_N_W_025=125, FX_N_W_050=250, FX_N_W_100=500)
    if got != exp:
        raise SystemExit(f"fx_config.h constants differ from the Python expressions: {got} vs {exp}")
    # tail / half-window helpers
    for nW, tail, half in ((125, 12, 37), (250, 25, 75), (500, 50, 150)):
        assert max(int(0.1 * nW), min(10, nW)) == tail and int(0.3 * nW) == half
    print("fx_config.h constants verified:", got)


def sos_rows(sos):
    return ",\n".join(f"    {{ {hx(b0)}, {hx(b1)}, {hx(b2)}, {hx(a1)}, {hx(a2)} }}"
                      for b0, b1, b2, a0, a1, a2 in sos)


def write_filter_data(sos_bp, sos_aa, zi_aa):
    assert np.allclose(sos_bp[:, 3], 1.0) and np.allclose(sos_aa[:, 3], 1.0)
    path = os.path.join(COMMON, "fx_filters_data.h")
    with open(path, "w", newline="\n", encoding="utf-8") as f:
        f.write(f"""/* fx_filters_data.h — generated by firmware/tools/export_filters.py (scipy {scipy.__version__});
 * do not edit. Coefficients are exact double literals; they convert to fx_iir_t at use.
 *   FX_SOS_BP: signal.butter(4, [1e3, 100e3], btype="bandpass", fs=500e3, output="sos")
 *   FX_SOS_AA: signal.butter(4, 0.4 * 5e3, fs=500e3, output="sos")   (synth._aa_decimate)
 *   FX_AA_ZI:  signal.sosfilt_zi(FX_SOS_AA), to be scaled by the first sample */
#ifndef FX_FILTERS_DATA_H
#define FX_FILTERS_DATA_H
#include "fx_filters.h"

static const fx_sos_t FX_SOS_BP[FX_N_SOS_BP] = {{
{sos_rows(sos_bp)}
}};

static const fx_sos_t FX_SOS_AA[FX_N_SOS_AA] = {{
{sos_rows(sos_aa)}
}};

static const double FX_AA_ZI[FX_N_SOS_AA][2] = {{
{(","+chr(10)).join(f"    {{ {hx(z[0])}, {hx(z[1])} }}" for z in zi_aa)}
}};

#endif /* FX_FILTERS_DATA_H */
""")
    print("wrote", path)


def c_array(name, ctype, vals, fmt, per_line=4):
    lines = []
    for i in range(0, len(vals), per_line):
        lines.append("    " + ", ".join(fmt(v) for v in vals[i:i + per_line]) + ",")
    return f"static const {ctype} {name}[{len(vals)}] = {{\n" + "\n".join(lines) + "\n};\n"


def write_test_vectors(sos_bp):
    N = 4000
    rng = np.random.default_rng(20261001)
    k = np.arange(N)
    x = (0.5 * (k >= 500) + 0.3 * np.sin(2 * np.pi * 5e3 * k / FS)
         + 0.2 * np.sin(2 * np.pi * 50e3 * k / FS) * (k >= 2000)
         + 0.05 * (k >= 3000) * np.exp(-(k - 3000) / 200.0)
         + 0.01 * rng.standard_normal(N))
    x32 = x.astype(np.float32)
    xd = x32.astype(np.float64)
    zi = signal.sosfilt_zi(sos_bp)
    bp, _ = signal.sosfilt(sos_bp, xd, zi=zi * 0.0)
    aa = _aa_decimate(xd, FS, DECIM)
    ma5 = _movavg(xd, 5)
    path = os.path.join(TESTS, "fx_test_vectors.h")
    with open(path, "w", newline="\n", encoding="utf-8") as f:
        f.write("/* fx_test_vectors.h — generated by firmware/tools/export_filters.py; do not edit.\n"
                " * FX_TV_X: float32 test signal; FX_TV_BP: sosfilt(band-pass, zi=0) in float64;\n"
                " * FX_TV_AA: synth._aa_decimate(x, 500e3, 100); FX_TV_MA5: features._movavg(x, 5). */\n"
                "#ifndef FX_TEST_VECTORS_H\n#define FX_TEST_VECTORS_H\n\n")
        f.write(f"#define FX_TV_N {N}\n#define FX_TV_N_AA {aa.size}\n")
        f.write(f"#define FX_TV_MEAN {hx(xd.mean())}\n#define FX_TV_STD {hx(xd.std())}\n\n")
        f.write(c_array("FX_TV_X", "float", x32, hxf))
        f.write(c_array("FX_TV_BP", "double", bp, hx))
        f.write(c_array("FX_TV_MA5", "double", ma5, hx))
        f.write(c_array("FX_TV_AA", "double", aa, hx))
        f.write("\n#endif /* FX_TEST_VECTORS_H */\n")
    print("wrote", path)


def main():
    check_constants()
    sos_bp = signal.butter(4, [1e3, min(100e3, 0.4 * FS)], btype="bandpass", fs=FS, output="sos")
    sos_aa = signal.butter(4, 0.4 * F_SLOW, fs=FS, output="sos")
    zi_aa = signal.sosfilt_zi(sos_aa)
    assert sos_bp.shape[0] == 4 and sos_aa.shape[0] == 2
    write_filter_data(sos_bp, sos_aa, zi_aa)
    write_test_vectors(sos_bp)


if __name__ == "__main__":
    main()
