"""export_model.py — trained HistGradientBoostingClassifier(s) -> firmware/common/fx_model_data.h
(FIRMWARE_SPEC.md §6.3), and optionally the Python reference scores of a fixture feature table.

  python firmware/tools/export_model.py --models firmware/host/models/feeder.joblib \\
         firmware/host/models/rack.joblib firmware/host/models/both.joblib \\
         [--header firmware/common/fx_model_data.h] \\
         [--features firmware/host/tests/fixtures/reference_features.csv \\
          --scores firmware/host/tests/fixtures/reference_scores.csv]

The model name is the file stem (feeder | rack | both). Node layout: see fx_model.h. The
export walks clf._predictors[iteration][class].nodes (feature_idx, num_threshold,
missing_go_to_left, left, right, value, is_leaf) and stores thresholds and leaf values as
exact float64 (float32 thresholds flipped splits on grid-valued features); with --features it
re-walks the tables in numpy against clf.decision_function and prints the largest deviation
(the C test is the acceptance)."""
import argparse
import os
import sys
import time
import numpy as np
import pandas as pd
import joblib
import sklearn

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
sys.path.insert(0, ROOT)
from dcsim.features import ALL   # noqa: E402

CLASSES = ["ALERT", "HOLD", "TRIP"]
BOTH_COLS = ALL + [c + "_rack" for c in ALL]


def hx(v):
    v = float(v)
    if np.isnan(v):
        return "NAN"
    if np.isinf(v):                 # sklearn uses +inf thresholds for missing-value-only splits
        return "INFINITY" if v > 0 else "-INFINITY"
    return v.hex()


def flatten(clf):
    """-> (nodes list of (v float64, left, right, feat, flags), tree_start list)"""
    nodes, starts = [], [0]
    for it in clf._predictors:
        for pr in it:
            nd = pr.nodes
            if nd["is_categorical"].any():
                raise SystemExit("categorical splits are not supported")
            if len(nd) > 255:
                raise SystemExit(f"tree with {len(nd)} nodes exceeds the uint8 child index")
            for n in nd:
                leaf = bool(n["is_leaf"])
                v = float(n["value"]) if leaf else float(n["num_threshold"])
                flags = (1 if leaf else 0) | (2 if n["missing_go_to_left"] else 0)
                nodes.append((v, 0 if leaf else int(n["left"]), 0 if leaf else int(n["right"]),
                              0 if leaf else int(n["feature_idx"]), flags))
            starts.append(len(nodes))
    return nodes, starts


def walk_tables(nodes, starts, baseline, n_classes, X):
    """numpy re-walk of the exported tables (what the C code computes), row by row"""
    n_trees = len(starts) - 1
    out = np.tile(np.asarray(baseline, dtype=np.float64), (X.shape[0], 1))
    v = np.array([float(n[0]) for n in nodes]); left = np.array([n[1] for n in nodes])
    right = np.array([n[2] for n in nodes]); feat = np.array([n[3] for n in nodes]); flags = np.array([n[4] for n in nodes])
    for r in range(X.shape[0]):
        x = X[r]
        for t in range(n_trees):
            s = starts[t]; i = s
            while not (flags[i] & 1):
                xv = x[feat[i]]
                if np.isnan(xv):
                    i = s + (left[i] if flags[i] & 2 else right[i])
                else:
                    i = s + (left[i] if xv <= v[i] else right[i])
            out[r, t % n_classes] += v[i]
    return out


def emit_model(f, name, clf, nodes, starts):
    f.write(f"/* ---- {name}: {clf.n_iter_} iterations x {clf.n_trees_per_iteration_} classes, "
            f"{len(nodes)} nodes, {clf.n_features_in_} features */\n")
    f.write(f"static const fx_node_t fx_nodes_{name}[{len(nodes)}] = {{\n")
    for i in range(0, len(nodes), 4):
        f.write("    " + " ".join(f"{{{hx(v)},{l},{r},{ft},{fl}}}," for v, l, r, ft, fl in nodes[i:i + 4]) + "\n")
    f.write("};\n")
    f.write(f"static const uint32_t fx_tree_start_{name}[{len(starts)}] = {{\n")
    for i in range(0, len(starts), 16):
        f.write("    " + ",".join(str(s) for s in starts[i:i + 16]) + ",\n")
    f.write("};\n")
    base = np.asarray(clf._baseline_prediction, dtype=np.float64).ravel()
    f.write(f"static const fx_model_t fx_model_{name} = {{ \"{name}\", fx_nodes_{name}, fx_tree_start_{name}, "
            f"{len(nodes)}u, {len(starts) - 1}u, {clf.n_trees_per_iteration_}u, {clf.n_features_in_}u, "
            f"{{ {hx(base[0])}, {hx(base[1])}, {hx(base[2])} }} }};\n\n")


def export_header(models, header):
    """models: dict name -> clf. Returns dict name -> (n_nodes, bytes)."""
    info = {}
    with open(header, "w", newline="\n", encoding="utf-8") as f:
        f.write(f"/* fx_model_data.h — generated by firmware/tools/export_model.py on {time.strftime('%Y-%m-%d %H:%M')}"
                f" (scikit-learn {sklearn.__version__}); do not edit.\n"
                " * Training provenance: firmware/host/models/models.json. Node layout: fx_model.h. */\n"
                "#ifndef FX_MODEL_DATA_H\n#define FX_MODEL_DATA_H\n#include <math.h>\n#include \"fx_model.h\"\n\n")
        for name, clf in models.items():
            if list(clf.classes_) != CLASSES:
                raise SystemExit(f"{name}: classes {list(clf.classes_)} != {CLASSES}")
            nodes, starts = flatten(clf)
            emit_model(f, name, clf, nodes, starts)
            info[name] = dict(n_iter=int(clf.n_iter_), n_trees=len(starts) - 1, n_nodes=len(nodes),
                              bytes=len(nodes) * 12 + len(starts) * 4, n_features=int(clf.n_features_in_))
        f.write(f"#define FX_N_MODELS {len(models)}\n")
        f.write("static const fx_model_t *const FX_MODEL_TABLE[FX_N_MODELS] = { "
                + ", ".join(f"&fx_model_{n}" for n in models) + " };\n\n#endif /* FX_MODEL_DATA_H */\n")
    print("wrote", header, info)
    return info


def reference_scores(models, features_csv, scores_csv):
    # round_trip: pandas' default float parser is not correctly rounded and can land one ulp off a
    # value that sits exactly on a split threshold (t_rise = 0.03 -> raw score off by 0.7)
    d = pd.read_csv(features_csv, dtype={"event": str, "node": str}, float_precision="round_trip")
    rows = []
    worst = {}
    for name, clf in models.items():
        if name == "both":
            fe = d[d.node == "feeder"].reset_index(drop=True)
            ra = d[d.node == "rack"].set_index(["event", "W_ms"])
            keep = [i for i, (e, w) in enumerate(zip(fe.event, fe.W_ms)) if (e, w) in ra.index]
            fe = fe.iloc[keep].reset_index(drop=True)
            X = np.column_stack([fe[ALL].values.astype(np.float64),
                                 ra.loc[list(zip(fe.event, fe.W_ms)), ALL].values.astype(np.float64)])
            sub, node = fe, "both"
        else:
            sub = d[d.node == name].reset_index(drop=True)
            X = sub[ALL].values.astype(np.float64)
            node = name
        if len(sub) == 0:
            continue
        raw = clf.decision_function(X)
        proba = clf.predict_proba(X)
        am = np.array(CLASSES)[raw.argmax(1)]
        nodes, starts = flatten(clf)
        dev = np.abs(walk_tables(nodes, starts, np.asarray(clf._baseline_prediction).ravel(), 3, X) - raw).max()
        worst[name] = float(dev)
        for i in range(len(sub)):
            rows.append(dict(event=sub.event.iloc[i], node=node, W_ms=sub.W_ms.iloc[i], model=name,
                             raw_ALERT=raw[i, 0], raw_HOLD=raw[i, 1], raw_TRIP=raw[i, 2],
                             p_ALERT=proba[i, 0], p_HOLD=proba[i, 1], p_TRIP=proba[i, 2], argmax=am[i]))
    out = pd.DataFrame(rows)
    out.to_csv(scores_csv, index=False, float_format="%.17g")
    print(f"wrote {scores_csv}: {len(out)} rows; exported-table re-walk vs decision_function, max |diff|: {worst}")
    return worst


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--models", nargs="+", required=True, help="joblib files; name = file stem")
    ap.add_argument("--header", default=os.path.join(ROOT, "firmware", "common", "fx_model_data.h"))
    ap.add_argument("--features", help="fixture reference_features.csv")
    ap.add_argument("--scores", help="output reference_scores.csv (with --features)")
    a = ap.parse_args()
    models = {os.path.splitext(os.path.basename(p))[0]: joblib.load(p) for p in a.models}
    export_header(models, a.header)
    if a.features and a.scores:
        reference_scores(models, a.features, a.scores)


if __name__ == "__main__":
    main()
